# Testing "My Solver" depending on CVXPY 

In [1]:
from Simplex_Solver import simplex as splx
import numpy as np
import cvxpy as cp

In [2]:
# Objective 
def f(X, c):
    return c@X

In [3]:
# Constraints
def g(X, A, b):
    L = A@X - b
    return L

## $1^{st}$ Problem 
$$\min_{x \in \mathbb{R}^4, x \geq 0} -7x_1 - 9x_2 - 18x_3 -17x_4$$
subject to:- 
$$\begin{cases} 2x_1 + 4x_2 + 5x_3 + 7x_4 \leq 41  \\ x_1 + x_2 + 2x_3 + 2x_4 \leq 17 \\ x_1 + 2x_2 + 3x_3 + 3x_4 \leq 24\end{cases}$$

In [4]:
c1 = np.array([-7, -9, -18, -17])
Al1 = np.array([[2,4,6,7],[1,1,2,2],[1,2,3,3]])
bl1 = np.array([41,17,24])

In [5]:
x1 = cp.Variable(len(c1))
objective1 = cp.Minimize(f(x1, c1))
constraints1 = [g(x1, Al1, bl1) <= 0, x1>=0]
LP1 = cp.Problem(objective1, constraints1)
res1 = LP1.solve(solver = cp.CPLEX)
print('Objective Value = ', res1)
print('Solution: ', x1.value)
print('Dual Solution: ', constraints1[0].dual_value)

Objective Value =  -133.0
Solution:  [10.   0.   3.5  0. ]
Dual Solution:  [ 2.  3. -0.]


In [6]:
result1, table1, X1, Y1, F1, ite1 = splx(c1, Al1, bl1)
print(result1)

-----  ---  ---  ----  ----  ---  ---  ---  --------
Basic  x1   x2   x3    x4    s1   s2   s3   Solution
z      7.0  9.0  18.0  17.0  0.0  0.0  0.0  0.0
s1     2    4    6     7     1.0  0.0  0.0  41
s2     1    1    2     2     0.0  1.0  0.0  17
s3     1    2    3     3     0.0  0.0  1.0  24
-----  ---  ---  ----  ----  ---  ---  ---  --------
OPI =  [[1.0 0.0 0.0]
 [0.0 1.0 0.0]
 [0.0 0.0 1.0]]
OOC =  [0. 0. 0.]
-----  -------------------  --------------------  ---  -------------------  -------------------  ---  ---  -----------------
Basic  x1                   x2                    x3   x4                   s1                   s2   s3   Solution
z      1.0                  -3.0                  0.0  -4.0                 -3.0                 0.0  0.0  -123.0
x3     0.3333333333333333   0.6666666666666666    1.0  1.1666666666666667   0.16666666666666666  0.0  0.0  6.833333333333333
s2     0.33333333333333337  -0.33333333333333326  0.0  -0.3333333333333335  -0.3333333333333333  1.0 

## $2^{nd}$ Problem 
$$\max ~ 5x_1 + 12x_2 + 4x_3$$
subject to:- 
$$\begin{cases} x_1 + 2x_2 + x_3 \leq 10  \\ 2x_1 - x_2 + 3x_3 = 8 \end{cases}$$

In [7]:
c2 = np.array([5,12,4])
Al2 = np.array([1,2,1])
bl2 = np.array([10])
Ae2 = np.array([2,-1,3])
be2 = np.array([8])

In [8]:
x2 = cp.Variable(len(c2))
objective2 = cp.Maximize(f(x2, c2))
constraints2 = [g(x2, Al2, bl2) <= 0, g(x2, Ae2, be2) == 0 ,x2>=0]
LP2 = cp.Problem(objective2, constraints2)
res2 = LP2.solve(solver = cp.CPLEX)
print('Objective Value = ', res2)
print('Solution: ', x2.value)
print('Dual Solution: ', [constraints2[0].dual_value, constraints2[1].dual_value])

Objective Value =  54.8
Solution:  [5.2 2.4 0. ]
Dual Solution:  [array([5.8]), array([-0.4])]


In [9]:
result2, table2, X2, Y2, F2, ite2 = splx(c2, Al2, bl2, Ae=Ae2, be=be2, Big_M = True, obj = 'Max')
print(result2)

-----  -----  -----  -----  ---  ---  --------
Basic  x1     x2     x3     s1   R1   Solution
z      205.0  -88.0  304.0  0.0  0.0  800.0
s1     1      2      1      1.0  0.0  10
R1     2      -1     3      0.0  1.0  8
-----  -----  -----  -----  ---  ---  --------
OPI =  [[1.0 0.0]
 [0.0 1.0]]
OOC =  [   0. -100.]
-----  -------------------  -------------------  ---  ---  -------------------  -------------------
Basic  x1                   x2                   x3   s1   R1                   Solution
z      2.333333333333343    13.333333333333329   0.0  0.0  -101.33333333333333  -10.666666666666629
s1     0.33333333333333337  2.3333333333333335   0.0  1.0  -0.3333333333333333  7.333333333333334
x3     0.6666666666666666   -0.3333333333333333  1.0  0.0  0.3333333333333333   2.6666666666666665
-----  -------------------  -------------------  ---  ---  -------------------  -------------------
OPI =  [[1.0 -0.3333333333333333]
 [0.0 0.3333333333333333]]
OOC =  [0. 4.]
-----  --------------

In [10]:
result22, table22, X22, Y22, F22, ite22 = splx(c2, Al2, bl2, Ae=Ae2, be=be2, obj = 'Max')
print(result22)

-----  ---  ----  ---  ---  ---  --------
Basic  x1   x2    x3   s1   R1   Solution
r      2.0  -1.0  3.0  0.0  0.0  8.0
s1     1    2     1    1.0  0.0  10
R1     2    -1    3    0.0  1.0  8
-----  ---  ----  ---  ---  ---  --------
OPI =  [[1.0 0.0]
 [0.0 1.0]]
OOC =  [0. 0.]
-----  -------------------  -------------------  ---  ---  -------------------  ------------------
Basic  x1                   x2                   x3   s1   R1                   Solution
r      0.0                  0.0                  0.0  0.0  -1.0                 0.0
s1     0.33333333333333337  2.3333333333333335   0.0  1.0  -0.3333333333333333  7.333333333333334
x3     0.6666666666666666   -0.3333333333333333  1.0  0.0  0.3333333333333333   2.6666666666666665
-----  -------------------  -------------------  ---  ---  -------------------  ------------------
OPI =  [[1.0 -0.3333333333333333]
 [0.0 0.3333333333333333]]
OOC =  [0. 4.]
-----  -------------------  -------------------  ---  ---  ------------------

## $3^{rd}$ Problem 
$$\min ~ 4x_1 + x_2 $$
subject to:- 
$$\begin{cases} 3x_1 + x_2 = 3  \\ 4x_1 + 3x_2 \geq 6 \\ x_1 + 2x_2 \leq 4 \end{cases}$$

In [11]:
c3 = np.array([4,1])
Al3 = np.array([1,2])
bl3 = np.array([4])
Ag3 = np.array([4,3])
bg3 = np.array([6])
Ae3 = np.array([3,1])
be3 = np.array([3])

In [12]:
x3 = cp.Variable(len(c3))
objective3 = cp.Minimize(f(x3, c3))
constraints3 = [g(x3, Al3, bl3) <= 0, g(x3, Ag3, bg3) >= 0, g(x3, Ae3, be3) == 0 ,x3>=0]
LP3 = cp.Problem(objective3, constraints3)
res3 = LP3.solve(solver = cp.CPLEX)
print('Objective Value = ', res3)
print('Solution: ', x3.value)
print('Dual Solution: ', [constraints3[0].dual_value, constraints3[1].dual_value, constraints3[2].dual_value])

Objective Value =  3.4000000000000004
Solution:  [0.4 1.8]
Dual Solution:  [array([0.2]), array([-0.]), array([-1.4])]


In [13]:
result3, table3, X3, Y3, F3, ite3 = splx(c3, Al3, bl3, Ag3, bg3, Ae3, be3, Big_M = True)
print(result3)

-----  -----  -----  ------  ---  ---  ---  --------
Basic  x1     x2     p1      s1   R1   R2   Solution
z      696.0  399.0  -100.0  0.0  0.0  0.0  900.0
s1     1      2      0.0     1.0  0.0  0.0  4
R1     4      3      -1.0    0.0  1.0  0.0  6
R2     3      1      0.0     0.0  0.0  1.0  3
-----  -----  -----  ------  ---  ---  ---  --------
OPI =  [[1.0 0.0 0.0]
 [0.0 1.0 0.0]
 [0.0 0.0 1.0]]
OOC =  [   0. -100. -100.]
-----  ---  ------------------  ------  ---  ---  -------------------  --------
Basic  x1   x2                  p1      s1   R1   R2                   Solution
z      0.0  167.0               -100.0  0.0  0.0  -232.0               204.0
s1     0.0  1.6666666666666667  0.0     1.0  0.0  -0.3333333333333333  3.0
R1     0.0  1.6666666666666667  -1.0    0.0  1.0  -1.3333333333333333  2.0
x1     1.0  0.3333333333333333  0.0     0.0  0.0  0.3333333333333333   1.0
-----  ---  ------------------  ------  ---  ---  -------------------  --------
OPI =  [[1.0 0.0 -0.33333333333

In [14]:
result3, table3, X3, Y3, F3, ite3 = splx(c3, Al3, bl3, Ag3, bg3, Ae3, be3)
print(result3)

-----  ---  ---  ----  ---  ---  ---  --------
Basic  x1   x2   p1    s1   R1   R2   Solution
r      7.0  4.0  -1.0  0.0  0.0  0.0  9.0
s1     1    2    0.0   1.0  0.0  0.0  4
R1     4    3    -1.0  0.0  1.0  0.0  6
R2     3    1    0.0   0.0  0.0  1.0  3
-----  ---  ---  ----  ---  ---  ---  --------
OPI =  [[1.0 0.0 0.0]
 [0.0 1.0 0.0]
 [0.0 0.0 1.0]]
OOC =  [0. 0. 0.]
-----  ---  ------------------  ----  ---  ---  -------------------  --------
Basic  x1   x2                  p1    s1   R1   R2                   Solution
r      0.0  1.666666666666667   -1.0  0.0  0.0  -2.333333333333333   2.0
s1     0.0  1.6666666666666667  0.0   1.0  0.0  -0.3333333333333333  3.0
R1     0.0  1.6666666666666667  -1.0  0.0  1.0  -1.3333333333333333  2.0
x1     1.0  0.3333333333333333  0.0   0.0  0.0  0.3333333333333333   1.0
-----  ---  ------------------  ----  ---  ---  -------------------  --------
OPI =  [[1.0 0.0 -0.3333333333333333]
 [0.0 1.0 -1.3333333333333333]
 [0.0 0.0 0.3333333333333333]]
